export const LANG_GROUPS = [
  {
    group: "Germanisch",
    langs: [
      { code: "de", label: "Deutsch" },
      { code: "en", label: "English" },
      { code: "nl", label: "Nederlands" },
      { code: "sv", label: "Svenska" },
      { code: "nb", label: "Norsk Bokmål" },
      { code: "nn", label: "Norsk Nynorsk" },
      { code: "da", label: "Dansk" },
      { code: "is", label: "Íslenska" },
    ],
  },
  {
    group: "Romanisch",
    langs: [
      { code: "fr", label: "Français" },
      { code: "es", label: "Español" },
      { code: "it", label: "Italiano" },
      { code: "pt", label: "Português" },
      { code: "la", label: "Latinus" },
      { code: "ro", label: "Română" },
      { code: "ca", label: "Català" },
      { code: "gl", label: "Galego" },
    ],
  },
  {
    group: "Slawisch & Europäisch",
    langs: [
      { code: "ru", label: "Русский" },
      { code: "pl", label: "Polski" },
      { code: "cs", label: "Čeština" },
      { code: "uk", label: "Українська" },
      { code: "bg", label: "Български" },
      { code: "sh", label: "Srpskohrvatski" },
      { code: "mk", label: "Македонски" },
      { code: "lv", label: "Latviešu" },
      { code: "lt", label: "Lietuvių" },
      { code: "el", label: "Ελληνικά" },
      { code: "hu", label: "Magyar" },
      { code: "fi", label: "Suomi" },
      { code: "ga", label: "Gaeilge" },
      { code: "cy", label: "Cymraeg" },
      { code: "eo", label: "Esperanto" },
    ],
  },
  {
    group: "Asiatisch & Weitere",
    langs: [
      { code: "zh", label: "中文" },
      { code: "ja", label: "日本語" },
      { code: "ko", label: "한국어" },
      { code: "ar", label: "العربية" },
      { code: "hi", label: "हिन्दी" },
      { code: "fa", label: "فارسی" },
      { code: "he", label: "עברית" },
      { code: "tr", label: "Türkçe" },
      { code: "vi", label: "Tiếng Việt" },
      { code: "th", label: "ภาษาไทย" },
      { code: "id", label: "Bahasa Indonesia" },
      { code: "tl", label: "Filipino" },
      { code: "hy", label: "Հայերե坮" },
      { code: "ka", label: "ქართული" },
      { code: "sw", label: "Kiswahili" },
    ],
  },
];
export const METER_LABELS = {
  iamb: "Jambus",
  trochee: "Trochäus",
  dactyl: "Daktylus",
  anapest: "Anapäst",
  spondee: "Spondeus",
  amphibrach: "Amphibrach",
  amphimacer: "Amphimakros",
  bacchius: "Bacchius",
  antibacchius: "Antibacchius",
  molossus: "Molossus",
};

export const SORT_MODES = [
  { value: "balanced", label: "Ausgewogen" },
  { value: "purity_desc", label: "Reinheit", dir: "desc" },
  { value: "purity_asc", label: "Reinheit", dir: "asc" },
  { value: "usefulness_desc", label: "Häufigkeit", dir: "desc" },
  { value: "usefulness_asc", label: "Häufigkeit", dir: "asc" },
  { value: "alpha_asc", label: "Alphabetisch", dir: "asc" },
  { value: "alpha_desc", label: "Alphabetisch", dir: "desc" },
];

export const EXAMPLE_WORDS = ["Zeit", "Tag", "Schön", "Glück"];

export const POS_LABELS = {
  noun: "Nomen",
  verb: "Verb",
  adj: "Adjektiv",
  adv: "Adverb",
  name: "Eigenname",
  particle: "Partikel",
  prep: "Präposition",
  pron: "Pronomen",
  num: "Numerale",
  interj: "Interjektion",
  intj: "Interjektion",
  conj: "Konjunktion",
  article: "Artikel",
  det: "Determinativ",
  prefix: "Präfix",
  suffix: "Suffix",
  infix: "Infix",
  interfix: "Interfix",
  circumfix: "Zirkumfix",
  affix: "Affix",
  combining_form: "Kombinierende Form",
  preverb: "Präverb",
  postp: "Postposition",
  circumpos: "Zirkumposition",
  ambiposition: "Ambiposition",
  prep_phrase: "Präpositionalphrase",
  adv_phrase: "Adverbialphrase",
  phrase: "Phrase",
  proverb: "Sprichwort",
  abbrev: "Abkürzung",
  contraction: "Kontraktion",
  counter: "Zählwort",
  classifier: "Klassifikator",
  adnominal: "Adnominal",
  character: "Schriftzeichen",
  syllable: "Silbe",
  symbol: "Symbol",
  punct: "Satzzeichen",
  root: "Wortwurzel",
  stem: "Wortstamm",
  romanization: "Romanisierung",
  "soft-redirect": "Weiterleitung",
};
