export const LANGS = [
  { code: "de", label: "Deutsch" },
  { code: "en", label: "English" },
];
export const METER_LABELS = {
  iamb: "Jambus",
  trochee: "Trochäus",
  dactyl: "Daktylus",
  anapest: "Anapäst",
  spondee: "Spondeus",
  amphibrach: "Amphibrach",
  amphimacer: "Amphimakros",
  bacchius: "Bacchius",
  antibacchius: "Antibacchius",
  molossus: "Molossus",
};

export const METER_PATTERNS = {
  iamb: "01",
  trochee: "10",
  dactyl: "100",
  anapest: "001",
  spondee: "11",
  amphibrach: "010",
  amphimacer: "101",
  bacchius: "011",
  antibacchius: "110",
  molossus: "111",
};

export const SORT_MODES = [
  { value: "balanced", label: "Ausgewogen" },
  { value: "purity_desc", label: "Reinheit", dir: "desc" },
  { value: "purity_asc", label: "Reinheit", dir: "asc" },
  { value: "usefulness_desc", label: "Häufigkeit", dir: "desc" },
  { value: "usefulness_asc", label: "Häufigkeit", dir: "asc" },
  { value: "alpha_asc", label: "Alphabetisch", dir: "asc" },
  { value: "alpha_desc", label: "Alphabetisch", dir: "desc" },
];

export const EXAMPLE_WORDS = ["Zeit", "Tag", "Schön", "Glück"];

export const POS_LABELS = {
  noun: "Nomen",
  verb: "Verb",
  adj: "Adjektiv",
  adv: "Adverb",
  name: "Eigenname",
  particle: "Partikel",
  prep: "Präposition",
  pron: "Pronomen",
  num: "Numerale",
  interj: "Interjektion",
  intj: "Interjektion",
  conj: "Konjunktion",
  article: "Artikel",
  det: "Determinativ",
  prefix: "Präfix",
  suffix: "Suffix",
  infix: "Infix",
  interfix: "Interfix",
  circumfix: "Zirkumfix",
  affix: "Affix",
  combining_form: "Kombinierende Form",
  preverb: "Präverb",
  postp: "Postposition",
  circumpos: "Zirkumposition",
  ambiposition: "Ambiposition",
  prep_phrase: "Präpositionalphrase",
  adv_phrase: "Adverbialphrase",
  phrase: "Phrase",
  proverb: "Sprichwort",
  abbrev: "Abkürzung",
  contraction: "Kontraktion",
  counter: "Zählwort",
  classifier: "Klassifikator",
  adnominal: "Adnominal",
  character: "Schriftzeichen",
  syllable: "Silbe",
  symbol: "Symbol",
  punct: "Satzzeichen",
  root: "Wortwurzel",
  stem: "Wortstamm",
  romanization: "Romanisierung",
  "soft-redirect": "Weiterleitung",
};
